#!/bin/sh
echo "\033[01;34m
                                                                     ,########,
                                                                   ,#############,
                                                           ,####,,################,
                                                         ,######,##################,
                                                         ######,####################,####o
                                                        ,###### ,########,######,###,######o
                                                         #'oOOOOO,OOOO,OOOOOOOOOOOO,OOOOOOOOo
                                                      ,oOOOOOOOOOO,o,OOOOOOOOOOOOOOOOO OOOOOo,
                                                     ,oOOOOOOOOOOO,OOOOOOOOOOOOOOOOOOOOO OOo OOOO,
                                                ,,OO OOOOOOOOOOOo,OOOOOOOOOOOOOOOOOOOOOOO oOOOOOOOOO,
                                             ,OOOOOO oOOOOOOOOOO OOOOOOOOOOOOOOOOOOOOOOOOO OOOOOOOOOOO,
                                            ,%%%%%%% %%%%%%%%%%%,%%%%%%%%%%%%%%%%%%%%%%%%%,%%%%%%%%%%%%%
                                           ,%%%%%%%%% %%%%%%%%%%,%%%%%%%%%%%%%%%%%%%%%%%%%,%%%%%%%%%%%%%%
                                           %%%%%%%%%%%% %%%%,%%% %%%%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%% %%,
                                          ,%%%%%%%%%%%%%%% %%%%%,%%%%%%%%%%%%%%%%%%%%%%%%%,%%%%%%%%%%%%%%,%%%%,
                                           %%%%%%%%%%%%%% %%%%%%% %%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%%% %%%%%%
                                           ,%%%%%%%%%%%%%,%%%%%%%%,%%%%%%%%%%%%%%%%%%%%%,%%%%%%%%%%%%%%% %%%%%%%\033[00;34m      dd
\033[01;34m                                              %%%%%%%%%%% %%%%%%%%%% %%%%%%%%%%%%%%%%  %%%%%%%%%%%%%%% %%%%%%%%\033[00;34m       dd
\033[01;34m                                                %%%%%%%     %%%%%%%     o%%%%%%%%%o       %%%%%%%%%%    %%%%%\033[00;34m         dd
                                                        *cc          ll                                               dd
                                                      *cc            ll                                               dd
                                                     *cc             ll                                         ......dd
\033[00;33m    ,ooooooo,    *ww     ww     *ww   nnnnnnnnnnn  \033[00;34m  ccc             ll      ,ooooooo,     uu        *uu    ,ddddddddddd
\033[00;33m   oo       oo   *ww     ww     *ww  ,nn       *n* \033[00;34m  ccc             ll     oo       oo    uu        *uu   dd         dd
\033[00;33m  oo         oo, *ww     ww     *ww  nn         nn*\033[00;34m  ccc             ll    oo         oo,  uu        *uu  *d*         dd
\033[00;33m  oo         oo* *ww     ww     *ww  nn         nn*\033[00;34m   cc*            ll    oo         oo*  uu        *uu  *d*         dd
\033[00;33m   oo       oo   *ww    wwww    *ww  nn         nn*\033[00;34m    ccc*          ll,    oo       oo    uuu      u*uu   dd         dd
\033[00;33m    ,ooooooo,     *WWwwwwwwwwwwWW*   nn         nn*\033[00;34m       ccc*        lll*   ,ooooooo,       uuuuuuuuu      ddddddddddd
\033[00;33m      ''o''          ,ww    ,ww      nn         nn*\033[00;34m           cc        ll     ''o''           ''u''           'ddd''
\033[0m\n"
